theme: jekyll-theme-cayman
title: Shuxuan Guo
description: Shuxuan's Homepage
author : 
   name : Shuxuan Guo
   email : gsxuan.nudt@gmail.com
   github : ShuxuanGuo
   twitter : username
   feedburner : feedname
   comments :
provider: 
