theme: jekyll-theme-cayman
title: Shuxuan Guo
description: Shu  

gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   
   
sitemap:
   "About me":

author:
  name: Shuxuan Guo
  email: "gsxuan.nudt@gmail.com"
  facebook: yourname  # eg. daattali
  github: Shuxuan Guo    # eg. daattali
  twitter: yourname   # eg. daattali
  reddit: yourname    # eg. daattali
  google-plus: +yourname   # eg. +DeanAttali or 109424658772469020925
  linkedin: yourname  # eg. daattali
  xing: yourname      # eg. daattali
  stackoverflow: yourlink  # eg. "3943160/daattali"
  snapchat: yourname  # eg. daattali
  instagram: yourname # eg. daattali
  youtube: yourlink   # eg. user/daattali or channel/daattali
  spotify: yourname   # eg. daattali
  telephone: yourphone   # eg. +14159998888

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  google-plus: false
  github: true
  reddit: false
  linkedin: false
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: false
  spotify: false
  telephone: false
