theme: jekyll-theme-architect
title: Shuxuan Guo
description: Shuxuan Guo
author : 
   name : Shuxuan Guo
   email : gsxuan.nudt@gmail.com
   github : ShuxuanGuo
   twitter : username
   feedburner : feedname
   comments :
provider : disqus

disqus :
